apiVersion: wkp.weave.works/v1alpha1
kind: Workspace
metadata:
  name: demo
  namespace: wkp-workspaces
spec:
  interval: 1m
  suspend: false
  gitProvider:
    type: github
    hostname: github.com
    tokenRef:
      name: github-token # the git provider token created previously
  gitRepository:
    name: my-wkp-workspace # <- specify repository name
    owner: wkp-example-org # <- replace org with your GitHub organization
    teams:
      - team-alpha # <- specify which teams should be given access to the repository (optional)
  clusterScope:
    role: namespace-admin
    namespaces:
      - name: demo-app # <- target namespace
        resourceQuota: # <- optional field, defines a resource quota for namespace
          hard:
            requests.cpu: "2"
            requests.memory: 1Gi
            limits.cpu: "1"
            limits.memory: 2Gi
      - name: demo-db # <- another target namespace
        limitRange:   # <- optional field, defines a limit range for namespace
          limits:
          - type: Container
            max:
              memory: 2Gi
            min:
              memory: 501Mi
    networkPolicy: workspace-isolation

